### ISSUE TITLE
Minor licensing inconsistency

### ISSUE THREAD

**Issue by kentfredric** [glasswalk3r/archive-tar-wrapper-perl#17]
File | Indicated License
------|------------
LICENSE | GPL-3
lib/Archive/Tar/Wrapper.pm | GPL-3+
Makefile.PL | GPL-3
eg/tarflat | **perl**
META.yml | gpl
README.md | GPL-3+
META.json | GPL-3

The biggest outlier here being `eg/tarflat`

https://github.com/glasswalk3r/archive-tar-wrapper-perl/blob/e93747f880f7e4650d9bf3f7bf75f05f862db389/eg/tarflat#L89-L98

It may not be legally viable to fix this or whatever, but I thought I'd just raise this in case the situation can be improved.

**Comment by glasswalk3r** [comment]
Thank you for reporting this issue!

Please see this [branch](https://github.com/glasswalk3r/archive-tar-wrapper-perl/tree/bugfix/issue_17), that should fix the licenses.

Regarding `META.yml` showing `gpl` instead of `GPL-3`, it seems there is nothing I can do about it since `META.yml` uses an old specification, even though I specifying the expected GPL-3 value. See [here](http://blogs.perl.org/users/kentnl_kent_fredric/2012/05/ensure-abstract-and-license-fields-in-your-meta.html) for more details.

**Comment by kentfredric** [comment]
Yeah,  the thing with META.yml is **somewhat** expected,  but was mostly presented as evidence that "perl" is the outlier.

**Comment by glasswalk3r** [comment]
I understand. I missed that script, but now should be fixed.
Could you please take a shot and see if now it's fixed? Pretty simple, but a fresh pair of eyes always get extra things. :smiley:

**Comment by kentfredric** [comment]
Yeah, seems better now. :+1:

I have a tiny little script that just does some pretty crude grepping of certain keywords that I've been pointing at every CPAN dist I vendorize, and its crudeness makes it very sensitive at detecting obscure outliers ^_^

**Comment by glasswalk3r** [comment]
Hi there,

Just release version 0.38 that fixes those license issues.

Regarding this script of yours, I suggest you to take it to the CPAN testers.

A while ago I suggested that our smoker execute some "basic" tests (not distribution dependent) automatically, I guess this script of your would be a strong candidate for that.

You can reach the CPAN testers mailing list here: [https://lists.perl.org/list/cpan-testers-discuss.html](https://lists.perl.org./list/cpan-testers-discuss.html).

For now I'm closing this issue. Thanks again!
