### ISSUE TITLE
Confusing license

### ISSUE THREAD

**Issue by coolo** [glasswalk3r/archive-tar-wrapper-perl#5]
Hi,

Your README says 'same license as perl' but you added a GPL-3, which is not as perl itself. Your license in MakeMaker says 'gpl', which is not even an option in http://search.cpan.org/~dagolden/CPAN-Meta-2.150010/lib/CPAN/Meta/Spec.pm#license

Please make up your mind, you're making it hard for distributions to clarify your intentions.

**Comment by glasswalk3r** [comment]
Having the `LICENSE` file together with the distribution should be enough for anyone to be at easy regarding licensing, but I fixed the mixed descriptions anyway at commit 6069aa8d443bd1bc45743c56dab02406ba24333e.
Please evaluate and let me know.

**Comment by glasswalk3r** [comment]
I understand that the release 0.28 fix this issue, so I'm closing it.

**Comment by coolo** [comment]
excellent, thanks

**Comment by gregoa** [comment]
Do we have a public trail of the copyright holder (Mike Schilli)'s approval of the change of license of his code? Otherwise I'm afraid this doesn't work like that …

(I'm looking at updating the Debian package.)

**Comment by coolo** [comment]
taking 'GPL 1 or later' code and rereleasing it as GPL 3 is legit. Those who prefer Artistic or GPL 1 can still take the original code released as such.

**Comment by glasswalk3r** [comment]
@gregoa , you can check the permissions given by Mike [here](https://metacpan.org/permission/distribution/Archive-Tar-Wrapper). I'm officially the maintainer.
Besides that, I don't see how come using GPL 3 would be an issue to release a packaged version of the distribution on Debian.

**Comment by gregoa** [comment]
On Sun, 24 Jun 2018 07:33:59 -0700, Alceu Rodrigues de Freitas Junior wrote:

> @gregoa , you can check the permissions given by Mike
> [here](https://metacpan.org/permission/distribution/Archive-Tar-Wrapper).
> I'm officially the maintainer.

That was not my question :)

> Besides that, I don't see how come using GPL 3 would be an issue to
> release a packaged version of the distribution on Debian.

GPL-3 is of course no problem; I was just a bit hesitant because
changing _someone else's_ license triggered a warning in the back of
my head.

But yeah, that's probably allowed by the original license, so sorry
for the false alarm. 


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: Supertramp: Hide In Your Shell

**Comment by glasswalk3r** [comment]
@gregoa ,

> That was not my question :)

But I'm afraid that is what I have. :-)

There is a reason for GPL-3 being released, and that's why I "upgraded" the licensing.

But I understand the concern. I just picked up from where Mike stopped and thought that releasing as GPL-3 was a good choice to protect the freedoms of the project.
